workflows:
  ios-appetize:
    name: iOS Simulator Build for Appetize
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build for Simulator
        script: |
          # این دستور خروجی مخصوص شبیه‌ساز می‌سازد که نیاز به امضای اپل ندارد
          flutter build ios --simulator --debug
      - name: Prepare for Appetize
        script: |
          # فشرده‌سازی فایل برای آپلود راحت در سایت
          cd build/ios/iphonesimulator
          zip -r ios_simulator_app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/*.zip
