workflows:
  ios-appetize:
    name: iOS Simulator Build for Appetize
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Set up Flutter
        script: |
          flutter channel stable
          flutter upgrade
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for Simulator
        script: |
          # استفاده از دستور دقیق برای ساخت نسخه شبیه‌ساز
          flutter build ios --simulator --debug --no-codesign
      - name: Prepare for Appetize
        script: |
          # رفتن به پوشه درست و زیپ کردن Runner.app
          cd build/ios/iphonesimulator
          zip -r ios_simulator_app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/*.zip
