workflows:
  ios-build:
    name: iOS Build No Sign
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Set up Flutter
        script: flutter channel stable && flutter upgrade
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS without signing
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
