scripts:
      - name: Set up Flutter and Dart
        script: |
          # اجبار کدمجیک به استفاده از نسخه جدیدتر یا آپدیت خودکار
          flutter channel stable
          flutter upgrade
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for Simulator
        script: |
          flutter build ios --simulator --debug
      - name: Prepare for Appetize
        script: |
          cd build/ios/iphonesimulator
          zip -r ios_simulator_app.zip Runner.app
